# Generated by Django 5.0.4 on 2024-04-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Footballers",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(max_length=100)),
                ("surname", models.TextField(max_length=100)),
                ("team_id", models.IntegerField(unique=True)),
            ],
        ),
    ]
