# Generated by Django 5.0.4 on 2024-04-11 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0003_events"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="team_id",
            new_name="footballer_id",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="name",
            new_name="match_type",
        ),
        migrations.RemoveField(
            model_name="events",
            name="surname",
        ),
        migrations.AddField(
            model_name="events",
            name="match_id",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="events",
            name="minute",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("host_team_id", models.IntegerField(unique=True)),
                ("guest_team_id", models.IntegerField(unique=True)),
                ("host_goals", models.IntegerField(default=0)),
                ("guest_goals", models.IntegerField(default=0)),
                ("events", models.ManyToManyField(to="FootballManager.events")),
            ],
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("priority", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FootballManager.footballers",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Statistics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("matches_played", models.IntegerField(default=0)),
                ("goals_scored", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("yellow_cards", models.IntegerField(default=0)),
                ("red_cards", models.IntegerField(default=0)),
                ("clean_sheets", models.IntegerField(default=0)),
                ("minutes_played", models.IntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FootballManager.footballers",
                    ),
                ),
            ],
        ),
    ]
