# Generated by Django 5.0.4 on 2024-04-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0004_rename_team_id_events_footballer_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="statistics",
            name="clean_sheets",
        ),
        migrations.AddField(
            model_name="statistics",
            name="season",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
