# Generated by Django 5.0.4 on 2024-04-11 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0005_remove_statistics_clean_sheets_statistics_season"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Events",
            new_name="Event",
        ),
        migrations.RenameModel(
            old_name="Footballers",
            new_name="Footballer",
        ),
        migrations.RenameModel(
            old_name="Statistics",
            new_name="Statistic",
        ),
        migrations.RenameModel(
            old_name="Teams",
            new_name="Team",
        ),
    ]
