# Generated by Django 5.0.4 on 2024-04-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "FootballManager",
            "0006_rename_events_event_rename_footballers_footballer_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="queue",
            old_name="player",
            new_name="footballer",
        ),
        migrations.RenameField(
            model_name="statistic",
            old_name="player",
            new_name="footballer",
        ),
        migrations.RemoveField(
            model_name="event",
            name="footballer_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="match_id",
        ),
        migrations.RemoveField(
            model_name="footballer",
            name="team_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="guest_team_id",
        ),
        migrations.RemoveField(
            model_name="match",
            name="host_team_id",
        ),
        migrations.AddField(
            model_name="event",
            name="footballer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FootballManager.footballer",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="match",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FootballManager.match",
            ),
        ),
        migrations.AddField(
            model_name="footballer",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FootballManager.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="guest_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest_team",
                to="FootballManager.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="host_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="host_team",
                to="FootballManager.team",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="match_type",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="footballer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="footballer",
            name="surname",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="match",
            name="events",
            field=models.ManyToManyField(
                related_name="events", to="FootballManager.event"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="season",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="team",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="team",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
