# Generated by Django 5.0.4 on 2024-04-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0007_rename_player_queue_footballer_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="match_type",
            new_name="type",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="footballer",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="priority",
        ),
        migrations.AddField(
            model_name="match",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="queue",
            name="match",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FootballManager.match",
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
