# Generated by Django 5.0.4 on 2024-04-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "FootballManager",
            "0008_rename_match_type_event_type_remove_queue_footballer_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="type",
            new_name="event_type",
        ),
    ]
