# Generated by Django 5.0.4 on 2024-04-13 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0009_rename_type_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="footballers",
            field=models.ManyToManyField(
                blank=True, related_name="footballer", to="FootballManager.footballer"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("GOAL", "Goal"),
                    ("YELLOW CARD", "Yellow Card"),
                    ("RED CARD", "Red Card"),
                ],
                default="GOAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="footballer",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team",
                to="FootballManager.team",
            ),
        ),
    ]
