# Generated by Django 5.0.4 on 2024-04-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "FootballManager",
            "0011_remove_match_events_remove_statistic_minutes_played_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="queue",
            old_name="status",
            new_name="position",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="match",
        ),
        migrations.RemoveField(
            model_name="queue",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="queue",
            name="matches",
            field=models.ManyToManyField(to="FootballManager.match"),
        ),
    ]
