# Generated by Django 5.0.3 on 2024-05-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballManager', '0013_remove_queue_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'Goal'), ('YELLOW CARD', 'Yellow card'), ('RED CARD', 'Red card')], default='GOAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
