# Generated by Django 5.0.3 on 2024-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballManager', '0015_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='trainer',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
