# Generated by Django 5.0.3 on 2024-05-15 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballManager', '0016_team_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('GOAL', 'Goal'), ('ASSIST', 'Assist'), ('YELLOW CARD', 'Yellow card'), ('RED CARD', 'Red card')], default='GOAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='FootballManager.match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='guest_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='host_goals',
            field=models.IntegerField(null=True),
        ),
    ]
