# Generated by Django 5.0.4 on 2024-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0017_alter_event_event_type_alter_event_match_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("GOAL", "Gol"),
                    ("ASSIST", "Asysta"),
                    ("YELLOW CARD", "Żółta kartka"),
                    ("RED CARD", "Czerwona kartka"),
                ],
                default="GOAL",
                max_length=20,
            ),
        ),
    ]
