# Generated by Django 5.0.4 on 2024-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0019_team_description_team_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="queue_number",
            field=models.IntegerField(default=1),
        ),
    ]
