# Generated by Django 5.0.3 on 2024-05-27 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballManager', '0020_queue_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='matches',
        ),
        migrations.AddField(
            model_name='match',
            name='queue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='FootballManager.queue'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
