# Generated by Django 5.0.4 on 2024-05-27 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0020_match_queue_number"),
        ("FootballManager", "0020_queue_number"),
    ]

    operations = []
