# Generated by Django 5.0.4 on 2024-05-27 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0021_merge_0020_match_queue_number_0020_queue_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="queue_number",
        ),
        migrations.AddField(
            model_name="team",
            name="queue_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="FootballManager.queue",
            ),
        ),
        migrations.AlterField(
            model_name="queue",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
