# Generated by Django 5.0.3 on 2024-05-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballManager', '0022_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='own_goals',
            field=models.IntegerField(default=0),
        ),
    ]
