# Generated by Django 5.0.3 on 2024-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FootballManager', '0023_statistic_own_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='trainer',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
