# Generated by Django 5.0.4 on 2024-05-29 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "FootballManager",
            "0022_remove_match_queue_number_team_queue_number_and_more",
        ),
        ("FootballManager", "0024_alter_team_trainer"),
    ]

    operations = []
