# Generated by Django 5.0.4 on 2024-05-29 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FootballManager", "0025_merge_20240529_1110"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="queue_number",
        ),
    ]
