services:
  - name: web
    env: python3
    startCommand: gunicorn FootballManager.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      DJANGO_SETTINGS_MODULE: "myproject.settings"
    healthCheckPath: "/"

buildCommand: "pip install -r requirements.txt"
